### ISSUE TITLE
没有找到 SQL 文件

### ISSUE THREAD

**Issue by NBSDx2J** [panda1079/u8sdkweb#1]
如题，麻烦提交下 SQL 文件

**Comment by panda1079** [comment]
已经添加上去了呢，希望大佬能指正一下错误，感谢

**Comment by NBSDx2J** [comment]
非大佬，像大佬学习中。感谢

**Comment by panda1079** [comment]
这个还是需要对接你们的u8后台才能进行打包呢，这个模块是留给你们自己配置的，希望这个建议对你有用。

**Comment by NBSDx2J** [comment]
我们不需要后台，所以我会移掉 U8 自己的后台。

**Comment by NBSDx2J** [comment]
mac 版本的有研究吗

**Comment by panda1079** [comment]
建议windows好点，毕竟会遇到很多不知名的兼容性问题

**Comment by NBSDx2J** [comment]
-^-,  iOS 的打包工具，哈哈。

**Comment by NBSDx2J** [comment]
没有呢，就研究过 Android 的。
想看看 iOS 的。

**Comment by panda1079** [comment]
iOS的主要是用工程母包，然后分发子包，然后打标志进去，再打包，然后签名。

**Comment by NBSDx2J** [comment]
能否共享下研究研究。

**Comment by panda1079** [comment]
抱歉，不希望共享这个项目

**Comment by NBSDx2J** [comment]
额，好的。
