### ISSUE TITLE
老哥，可以问下怎么可以监控到python打包的进度呀？

### ISSUE THREAD

**Issue by baidushanxi** [panda1079/u8sdkweb#2]
我在php里面执行

**Comment by baidushanxi** [comment]
嗯嗯。。。我看u8 demo里面可以看到百分比，不知道怎么做

**Comment by baidushanxi** [comment]
http://111.231.193.31:13330/            用户名和密码：root/111111

**Comment by panda1079** [comment]
在core里面有总调用步骤，你可以在那里面做个锚点记录一下估计就可以了
